version: "3"
services:
  postgres:
    build:
      context: ./pgml-extension/
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    volumes:
      - "pg_data:/var/lib/postgresql"
    command:
      - sleep
      - infinity
  # admin:
  #   build:
  #     context: ./pgml-admin/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   command:
  #     - ./manage.py runserver

volumes:
  pg_data:
